In [1]:
import numpy as np

In [2]:
row1=np.array([40,45,25,10])
row2=np.array([35,30,20,30])

In [6]:
sum_row1=np.sum(row1)
sum_row2=np.sum(row2)
sum_row1,sum_row2

(120, 115)

In [5]:
sum_calumn=row1+row2
sum_calumn

array([75, 75, 45, 40])

In [7]:
sum_row=np.array([sum_row1,sum_row2])
sum_row

array([120, 115])

In [8]:
for i in sum_row:
    for j in sum_calumn:
        print(i,j)

120 75
120 75
120 45
120 40
115 75
115 75
115 45
115 40


In [12]:
expected_value=[]
for i in sum_row:
    for j in sum_calumn:
        value=(i*j)/235
        expected_value.append(value)
expected_value


[38.297872340425535,
 38.297872340425535,
 22.97872340425532,
 20.425531914893618,
 36.702127659574465,
 36.702127659574465,
 22.02127659574468,
 19.574468085106382]

In [13]:
observation_value=np.array([40,45,25,10,35,30,20,30])
observation_value

array([40, 45, 25, 10, 35, 30, 20, 30])

In [15]:
chi_calc=np.sum((np.square(observation_value-expected_value))/expected_value)
chi_calc

13.788747987117553